### PR TITLE
Update tutorial

### PR DESCRIPTION
**Pull request by 2600box**
dependency for mongodb is not mentioned, so i added it.

### CODE REVIEW

**Comment by dweidenfeld** [comment]
Good hint, but I will wait with the merge, because maybe we will add boltdb support soon, so no mongo connection is required anymore ;)

**Comment by ajkis** [comment]
> Good hint, but I will wait with the merge, because maybe we will add boltdb support soon, so no mongo connection is required anymore ;)

great news

**Comment by 2600box** [comment]
sounds good

**Comment by dweidenfeld** [comment]
We will switch back to bolt ;)

**Pull request closed without merging**
