### PR TITLE
README: Add how to get a Team Drive Root Node ID

### PR DESCRIPTION
**Pull request by herver**
This follows #319 and contains quick instructions to get a Team Drive's Root-Node-ID

### CODE REVIEW

**Comment by chriskyfung** [comment]
@herver Thank you! It works.

**Comment by herver** [comment]
Thanks for spotting the typo :+1: , I've fixed it as you suggested

**Comment by hardlick** [comment]
HI, how i can install this new functionallity?
in the release page doesnt appear

**Comment by felixbuenemann** [comment]
@hardlick There is no new release, you'll have to compile yourself with golang:

```sh
go get -d -u github.com/dweidenfeld/plexdrive
```

Then install the binary from your `$GOPATH/bin` directory.

Currently go 1.13 is untested, so I'd recommend sticking to go 1.12.

**Comment by zmike808** [comment]
> @hardlick **There is no new release**, you'll have to compile yourself with golang:
> 
> ```shell
> go get -d -u github.com/dweidenfeld/plexdrive
> ```
> 
> Then install the binary from your `$GOPATH/bin` directory.
> 
> Currently go 1.13 is untested, so I'd recommend sticking to go 1.12.

Not that plexdrive needs much active development at this moment, granted there's always convience level features that could be added, should we just be forking like madmen if we are planning to make any significant changes? Or are you still planning to be active/involved enough to accept PRs?

I feel as if there's 5 different forks currently that have implemented a new feature or made an attempt at doing so and then only some of those actually made the effort to send a PR.

**Comment by felixbuenemann** [comment]
I can merge PRs, if the tests are green and they have at least one review.

That said I'm not a go programmer, so I'm somewhat limited in the changes I can make and review.

I'm also rather busy, so responses can be slow.

I don't think there's a need for forks, we just need one or more active maintainers on this repo and @dweidenfeld would probably be happy do help out with the necessary permissions.

I think if the problems with the Team Drive support are ironed out, it makes sense to make a new release.

**Pull request merged**
