### PR TITLE
[WIP] Use Bolt as a cache backend

### PR DESCRIPTION
**Pull request by xconstruct**
Hi,

Thanks for your great project. I didn't want to set up an external server for such a simple project, so I chose to replace MongoDB with [Bolt](https://github.com/boltdb/bolt) - which is a fast, thread-safe embedded key-value store written in Go. I whipped this up in one evening and didn't test it extensively yet, but in general it should work. I'll be running it on my server for the next weeks.

I'm submitting it here to gauge interest and get a bit of feedback, so please let me know if you are interested in merging this and I'll see if I can improve this.

Also, I didn't conduct any benchmarking - and never tested with MongoDB before, so I'm not sure of the performance differences. Bolt in general should be very fast when reading, but I didn't optimize my code for writing lots of randomly distributed KV pairs, and the initial sync seems to take a while on a spinning drive with 3 TB of GDrive data.

Bolt operates on byte slices only, so I chose the following DB layout:

* api_objects: ID as key, JSON-encoded APIObject as value
* idx_api_objects_by_parent: `parent/name` as key, object ID as value
* page_token: "t" as key, token string as value

### CODE REVIEW

**Comment by xconstruct** [comment]
Sorry, I didn't notice that your first version was implemented in Bolt as well.

I'll leave this PR open for discussion since I'd still be interested in optimizing the queries, but you may close it if you don't want to pursue it further.

**Comment by xconstruct** [comment]
I've now improved the write performance significantly by batching the updates into a single transaction.

**Comment by ajkis** [comment]
Do you have SSD, btw i think current mongo will do initial sync in ram (/dev/shm) and at the end write it to DB, its significant boost.

p.s. Personally I would also prefer bolt solution over full fledge database solution, but as far as I remember @dweidenfeld had some problems with it.

**Comment by seuffert** [comment]
Nice work, with this plexdrive could work on embedded devices again

**Comment by dweidenfeld** [comment]
I really like it too. But I need to test the performance. The initial sync performance is not that important, but the file listing performance.

Maybe someone could benchmark this version with the current mongo implementation? I have no time for this right now, because I want to finish my feature first.

@xconstruct Thank you for your support. Please wait till someone benchmarks both solutions (or you can do this by yourself). I will make a huge refactoring in a few days, then we'll have to adjust your code a bit ;)

**Comment by xconstruct** [comment]
So, I did some very limited benchmarking. I tested my bolt version from yesterday and the current master one (though I don't know if your refactoring has performance implications). I did an initial sync with both, restarted plexdrive and mongodb to clear the RAM, and then ran `time ls -lR /mntdir > result.txt` to iterate over all files. My machine has a spinning disk and 16 gigs of RAM, my GDrive is ~3 TB with 100k changes and the resulting directory listing is 170k lines long.

I reran the tests a few times and got on average 33 seconds for bolt, and a very stable 1:04 minutes for mongodb. Though there were a few Bolt outliers in the beginning where it took around 2:15 min that I could not reproduce in later tests. Maybe I had disk activity before or the faster results were cached somewhere. So it's still a bit up in the air, but at least they are in the same ballpark :)

Initial sync took around 8 min for bolt and 6 min for mongodb.

**Comment by dweidenfeld** [comment]
I tested it myself and got the same results.

Do you also tested the correctness? What about if a file is a child of 2 parents?

**Comment by xconstruct** [comment]
Nope, just tested the basic stuff. It would also be important to test moving/renaming of files and deletion, to see if the parent cleanup works as expected.

**Comment by dweidenfeld** [comment]
Okay renaming is not working currently because of the parental structure. I will take a look at it and try to fix it.

**Comment by dweidenfeld** [comment]
Thank you again :)

**Pull request closed without merging**
