### PR TITLE
Add mkdir

### PR DESCRIPTION
**Pull request by ErAzOr2k**

### CODE REVIEW

**Comment by dweidenfeld** [comment]
Could you please fix the conflicts... I have not the time today ;)

**Comment by ErAzOr2k** [comment]
done :)

**Comment by dweidenfeld** [comment]
One last thing... variable names should be written in lowercase ;) ... but I am still refactoring big parts of the project so I will do this by time.

**Comment by ErAzOr2k** [comment]
thanks for the hint. I'll consider it the next time :)

**Pull request merged**
