### PR TITLE
Add Team Drive support

### PR DESCRIPTION
**Pull request by YipYup**
Redo of PR #296

### CODE REVIEW

**Comment by YipYup** [comment]
This is definitely not a complete pull request. I'm just hoping to get the ball going by organizing what I could find on it.More work will need to be done to get support. 

Essentially we can either request the list of team drives using the google credentials already provided and stored, or the user can input the team drive ID manually.

Here's the big commit to rclone v1.37 where team drive support was added. Glancing through it there are some indicators of how they implemented it there.

https://github.com/ncw/rclone/commit/a5cfdfd233b1598bde50c1ddd563bfdba274ba6f

**Comment by felixbuenemann** [comment]
Yeah, it works if I manually specify the node id of the team drive.

So it looks like the only thing missing is adding a flow that allows to select the team drive by name when setting up plexdrive.

However for power-users this is already usable.

@YipYup Do you mind updating the README section on Root-Node-Id in this PR to mention that it can also be used to point at a Team Drive root or shared folder (mentioned in #130).

**Comment by EchterAgo** [comment]
I've used something pretty much like this. The issue I started to get is that there were nil change.File changes. I think these happen when you move files between different team drives.

I worked around it by adding a nil check and skip after "Log.Tracef("Change %v", change)", but I'm not sure if this is the correct way to do it. It works well for me so far.

**Comment by felixbuenemann** [comment]
@EchterAgo That's great input. Did the filesystem still report the proper state, if files where moved out of or into the mounted tream drive?

**Comment by felixbuenemann** [comment]
@YipYup If you're busy let me know and I can take care of the README updates myself.

**Comment by EchterAgo** [comment]
I haven't noticed anything wrong so far. I think you can test it by just
moving a set of files to a different team drive using the web interface.

**Comment by felixbuenemann** [comment]
Yeah, tat would work.

Btw. do you have your additional changes for Team Drive support available in a fork somewhere?

**Comment by EchterAgo** [comment]
Haven't pushed anything to github yet, maybe I'll do it tomorrow.

**Comment by felixbuenemann** [comment]
Great!

**Comment by TripleFrequency** [comment]
Since I am unaware of any changes you have made to the fork, I will point out that there was an issue I encountered when I had tested it originally.

I experienced a Segmentation Fault when running it with my changes. It wasn't something I had time to really look into, and I had to move on to other things, but I figured it is worth pointing out as something to consider moving forward.

**Comment by EchterAgo** [comment]
https://github.com/EchterAgo/plexdrive/commits/teamdrive

**Comment by Admin9705** [comment]
good  stuff yipyip

**Comment by felixbuenemann** [comment]
@EchterAgo Did you check wether the nil-check in `change.File` was still needed after you added the root-node-id filter?

**Comment by EchterAgo** [comment]
No, I haven't. That's a good question though, it might not be needed.

**Comment by Admin9705** [comment]
@EchterAgo good work, what do you have to do to make it work? Just through the normal process of it?

**Comment by EchterAgo** [comment]
You have to specify --root-node-id=<id> on the command line. I copied my root node id from my rclone config file.

**Comment by YipYup** [comment]
As I haven't been able to get the time for this, I am going to close this so that someone else can re-open / resubmit it. That way I'm not running point and holding it up.

**Comment by Nottt** [comment]
How do you get a root-node-id?

**Comment by EchterAgo** [comment]
@Nottt https://github.com/dweidenfeld/plexdrive#team-drive

**Comment by Nottt** [comment]
@EchterAgo doesn't work for me... see https://github.com/dweidenfeld/plexdrive/issues/333. 

What version you are using? My team drive ID should be `0AArHY_zU--mnUk9PVA` but it doesn't work. I don't know if it's because of the _ or --

**Comment by EchterAgo** [comment]
Are you even using git master? There is no released/binary version that has team drive support.

**Comment by Nottt** [comment]
I don't know how to use "git master" you mean compile it from source? I tried, but it complained about a lot of go dependencies, so if any kind soul can give us a linux amd64 executable with teamdrive support :pray:

**Comment by Pawliko** [comment]
Any chance for making it up to date? I mean to release new version with working team drive?

**Comment by Nottt** [comment]
I posted the solution on #333

**Pull request closed without merging**
